In [14]:
import yfinance as yf
import pandas as pd

Here I downloaded the VKTX stock data for the past 5 years. I used head() and tail() just to have a sanity check to ensure all data was in ascending order and loaded in properly.

In [15]:
vktx = yf.download("VKTX", period="5y", auto_adjust=True)
vktx.head()

[*********************100%***********************]  1 of 1 completed

Price      Close  High   Low  Open  Volume
Ticker      VKTX  VKTX  VKTX  VKTX    VKTX
Date
2021-10-28  5.97  5.99  5.72  5.80  493200
2021-10-29  5.82  6.01  5.82  5.99  356600
2021-11-01  6.14  6.14  5.78  5.85  793100
2021-11-02  6.37  6.38  6.00  6.10  606000
2021-11-03  6.58  6.62  6.27  6.36  820600

Using shape was useful because it showed me how many rows and columns were in the dataset, which helped me confirm the dataset size and understand how much data I was working with.

In [16]:
vktx.shape

(1254, 5)

In [17]:
vktx.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1254 entries, 2021-10-28 to 2026-10-27
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, VKTX)   1253 non-null   float64
 1   (High, VKTX)    1253 non-null   float64
 2   (Low, VKTX)     1253 non-null   float64
 3   (Open, VKTX)    1253 non-null   float64
 4   (Volume, VKTX)  1254 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.8 KB

Checking for null values was important to rule out any missing values which needed to be removed. The sum just provides how many missing values there were.

In [18]:
vktx.isnull().sum()

Price   Ticker
Close   VKTX      1
High    VKTX      1
Low     VKTX      1
Open    VKTX      1
Volume  VKTX      0
dtype: int64

Checking for duplicates was important since we do not want repeating rows.

In [19]:
vktx.duplicated().sum()

np.int64(0)

In [20]:
vktx.index.duplicated().sum()

np.int64(0)

In [21]:
vktx.index.is_monotonic_increasing # Sanity check to ensure ascending order

True

The describe() function is useful because it provides a statistical summary of the dataset. This helps identify unusual values or patterns, such as unexpectedly high or low values, that may need to be examined more closely.

In [22]:
vktx.describe()

Price         Close         High          Low         Open        Volume
Ticker         VKTX         VKTX         VKTX         VKTX          VKTX
count   1253.000000  1253.000000  1253.000000  1253.000000  1.254000e+03
mean      26.655064    27.557805    25.834056    26.696518  3.253314e+06
std       20.188432    20.983720    19.510048    20.270633  5.037711e+06
min        2.110000     2.150000     2.020000     2.110000  1.617000e+05
25%        9.100000     9.320000     8.658000     8.980000  1.366650e+06
50%       26.280001    27.040001    25.559999    26.350000  2.285000e+06
75%       34.939999    35.924999    33.889999    35.139999  3.624850e+06
max       94.500000    99.410004    88.610001    90.250000  9.644790e+07

The following lines of code was just to check whether any of the columns had any negative values which shouldn't be there. It was done as a sanity check.

In [23]:
vktx.reset_index(inplace=True)
vktx.columns = vktx.columns.droplevel(1)
vktx.head()

Price       Date  Close  High   Low  Open  Volume
0     2021-10-28   5.97  5.99  5.72  5.80  493200
1     2021-10-29   5.82  6.01  5.82  5.99  356600
2     2021-11-01   6.14  6.14  5.78  5.85  793100
3     2021-11-02   6.37  6.38  6.00  6.10  606000
4     2021-11-03   6.58  6.62  6.27  6.36  820600

In [24]:
print((vktx["Close"] <= 0).sum())
print((vktx["High"] <= 0).sum())
print((vktx["Low"] <= 0).sum())
print((vktx["Open"] <= 0).sum())
print((vktx["Volume"] < 0).sum())

0
0
0
0
0

In [25]:
(vktx["High"] < vktx["Low"]).sum()

np.int64(0)

Overall, the data itself was clean there wasn't anything that reall had to be done here. All data was saved to a csv which can be found in the folder within this colab.

In [ ]:
vktx.columns = vktx.columns.get_level_values(0)
vktx.to_csv("vktx.csv", vktx)

TypeError: NDFrame.to_csv() takes from 1 to 2 positional arguments but 3 were given