In [28]:
'''It reads daily close, high, low, open, and volume form the trading days in the five years period.'''
import yfinance as yf
import pandas as pd

#download five year data from Bloom Energy, adjusted for split-shares and dividends
be = yf.download("BE", period="5y", auto_adjust=True)
print(be.shape)
be.head()

[*********************100%***********************]  1 of 1 completed

(1254, 5)

Price           Close       High        Low       Open   Volume
Ticker             BE         BE         BE         BE       BE
Date
2021-10-28  29.250000  29.969999  27.850000  27.860001  6501400
2021-10-29  31.260000  31.320000  29.100000  29.129999  6181100
2021-11-01  32.349998  32.939999  31.340000  31.620001  6196600
2021-11-02  32.139999  32.626999  31.230000  32.139999  3988700
2021-11-03  31.969999  32.500000  30.370001  31.530001  3579300

In [29]:
# Bloom Energy has no dividend; it *never* split-share.
ticker = yf.Ticker("BE")
print(ticker.splits)
print(ticker.dividends)

Series([], Name: Stock Splits, dtype: object)
Series([], Name: Dividends, dtype: object)

Prices columns should only have two decimal points since no split-share took place.

In [30]:
price_cols = ["Close", "High", "Low", "Open"]
# be[price_cols] = be[price_cols].round(2)
be.head()

Price           Close       High        Low       Open   Volume
Ticker             BE         BE         BE         BE       BE
Date
2021-10-28  29.250000  29.969999  27.850000  27.860001  6501400
2021-10-29  31.260000  31.320000  29.100000  29.129999  6181100
2021-11-01  32.349998  32.939999  31.340000  31.620001  6196600
2021-11-02  32.139999  32.626999  31.230000  32.139999  3988700
2021-11-03  31.969999  32.500000  30.370001  31.530001  3579300

In [31]:
# No missing value, non invalid values, no duplication
print(be.isnull().sum())
print((be <= 0).sum())
print(be.index.duplicated().sum())

Price   Ticker
Close   BE        0
High    BE        0
Low     BE        0
Open    BE        0
Volume  BE        0
dtype: int64
Price   Ticker
Close   BE        0
High    BE        0
Low     BE        0
Open    BE        0
Volume  BE        0
dtype: int64
0

In [32]:
be.reset_index(inplace=True)
be.columns = be.columns.droplevel(1)
be.head()

Price       Date      Close       High        Low       Open   Volume
0     2021-10-28  29.250000  29.969999  27.850000  27.860001  6501400
1     2021-10-29  31.260000  31.320000  29.100000  29.129999  6181100
2     2021-11-01  32.349998  32.939999  31.340000  31.620001  6196600
3     2021-11-02  32.139999  32.626999  31.230000  32.139999  3988700
4     2021-11-03  31.969999  32.500000  30.370001  31.530001  3579300

In [33]:
# Save to CSV
be.to_csv("../Data/BE.csv", index = False)