In [43]:
import yfinance as yf
import pandas as pd

Here I downloaded the MSFT stock data for the past 5 years. I used head() and tail() just to have a sanity check to ensure all data was in ascending order and loaded in properly.

> Add blockquote

In [44]:
msft = yf.download("MSFT", period="5y", auto_adjust=True)
msft.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2021-10-28  311.287628  311.786676  308.418023  311.268415  26297900
2021-10-29  318.264740  318.629441  310.855645  311.076392  34766000
2021-11-01  316.105438  318.140056  313.226256  318.015287  27073200
2021-11-02  319.713959  320.021079  316.710008  317.007521  26487100
2021-11-03  320.548889  321.412638  317.333797  320.452911  21500100

In [45]:
msft.tail()

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2026-10-21  532.950012  533.280029  525.020020  529.440002  13940100
2026-10-22  521.080017  533.599976  520.299988  533.140015  21266600
2026-10-23  524.510010  525.770020  515.700012  517.750000  13671500
2026-10-26  532.599976  533.250000  521.690002  527.400024  19021000
2026-10-27  531.330017  534.700012  528.330994  532.349976  19419705

Using shape was useful because it showed me how many rows and columns were in the dataset, which helped me confirm the dataset size and understand how much data I was working with.

In [46]:
msft.shape

(1254, 5)

Info just provided me with each column and its datatype. This was also loaded into understand the specific data types I was dealing with which all looked good.

In [47]:
msft.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1254 entries, 2021-10-28 to 2026-10-27
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, MSFT)   1254 non-null   float64
 1   (High, MSFT)    1254 non-null   float64
 2   (Low, MSFT)     1254 non-null   float64
 3   (Open, MSFT)    1254 non-null   float64
 4   (Volume, MSFT)  1254 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.8 KB

Checking for null values was important to rule out any missing values which needed to be removed. The sum just provides how many missing values there were.

In [48]:
msft.isnull().sum()

Price   Ticker
Close   MSFT      0
High    MSFT      0
Low     MSFT      0
Open    MSFT      0
Volume  MSFT      0
dtype: int64

Checking for duplicates was important since we do not want repeating rows.

In [49]:
msft.index.duplicated().sum()

np.int64(0)

The describe() function is useful because it provides a statistical summary of the dataset. This helps identify unusual values or patterns, such as unexpectedly high or low values, that may need to be examined more closely.

In [50]:
msft.describe()

Price         Close         High          Low         Open        Volume
Ticker         MSFT         MSFT         MSFT         MSFT          MSFT
count   1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03
mean     371.025863   374.591531   367.227579   370.988154  2.678278e+07
std       86.846154    87.203263    86.461124    86.860649  1.237234e+07
min      207.343643   213.305079   206.550078   210.537280  5.855900e+06
25%      297.070946   299.713504   293.254188   297.473896  1.917508e+07
50%      387.011841   390.767725   381.552730   386.633515  2.390235e+07
75%      425.700218   429.796678   421.924516   427.217334  3.083092e+07
max      543.450012   551.150024   543.059998   549.795172  1.862016e+08

In [51]:
msft.reset_index(inplace=True)
msft.columns = msft.columns.droplevel(1)
msft.head()

Price       Date       Close        High         Low        Open    Volume
0     2021-10-28  311.287628  311.786676  308.418023  311.268415  26297900
1     2021-10-29  318.264740  318.629441  310.855645  311.076392  34766000
2     2021-11-01  316.105438  318.140056  313.226256  318.015287  27073200
3     2021-11-02  319.713959  320.021079  316.710008  317.007521  26487100
4     2021-11-03  320.548889  321.412638  317.333797  320.452911  21500100

The following lines of code was just to check whether any of the columns had any negative values which shouldn't be there. It was done as a sanity check.

In [52]:
print((msft["Close"] <= 0).sum())
print((msft["High"] <= 0).sum())
print((msft["Low"] <= 0).sum())
print((msft["Open"] <= 0).sum())
print((msft["Volume"] < 0).sum())

0
0
0
0
0

In [53]:
(msft["Volume"] < 0).sum()

np.int64(0)

I checked whether any Highs may be less than the lows. Even though it is highly unlikely for that to ever happen it was just an important sanity check.

In [54]:
(msft["High"] < msft["Low"]).sum()

np.int64(0)

In [55]:
msft.columns = msft.columns.get_level_values(0)
msft.head()

Price       Date       Close        High         Low        Open    Volume
0     2021-10-28  311.287628  311.786676  308.418023  311.268415  26297900
1     2021-10-29  318.264740  318.629441  310.855645  311.076392  34766000
2     2021-11-01  316.105438  318.140056  313.226256  318.015287  27073200
3     2021-11-02  319.713959  320.021079  316.710008  317.007521  26487100
4     2021-11-03  320.548889  321.412638  317.333797  320.452911  21500100

Overall, the data itself was clean there wasn't anything that reall had to be done here. All data was saved to a csv which can be found in the folder within this colab.

In [56]:
msft.to_csv("../Data/msft.csv", index = False)